  1 name: CI
  2 # Controls when the action will run. 
  3 on: pull_request
  4 
  5 jobs:
  6   Terrafrom:
  7     name: 'Terraform'
  8     runs-on: ubuntu-latest
  9     # Steps represent a sequence of tasks that will be executed as part of the job
 10     steps:
 11       - uses: actions/checkout@v2
 12       # Runs a single command using the runners shell
 13       - name: terraform init
 14         run: terraform init
 15         env:
 16           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 17           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
 18       # Runs a set of commands using the runners shell
 19       - name: terraform plan
 20         run: terraform plan
 21         env:
 22           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 23           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
~                                                                           
